from __future__ import annotations

from copy import deepcopy
from typing import Any


def fsf_piece(
    piece_type: str,
    role: str,
    *,
    black_role: str | None = None,
    custom_betza: str | None = None,
    synonym: tuple[str, str] | None = None,
) -> dict[str, Any]:
    black = black_role if black_role is not None else role.lower()
    white = role.upper()
    return {
        "type": piece_type,
        "fen": {"white": white, "black": black},
        "synonym": ({"white": synonym[0], "black": synonym[1]} if synonym is not None else None),
        "customBetza": custom_betza,
        "value": {"midgame": 0, "endgame": 0},
    }


def make_fsf_variant_info(
    *,
    name: str = "testvariant",
    template: str = "chess",
    start_fen: str = "8/8/8/8/8/8/8/K6k w - - 0 1",
    width: int = 8,
    height: int = 8,
    pieces: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    pieces = pieces or [
        fsf_piece("pawn", "p"),
        fsf_piece("knight", "n"),
        fsf_piece("bishop", "b"),
        fsf_piece("rook", "r"),
        fsf_piece("queen", "q"),
        fsf_piece("king", "k"),
    ]
    piece_types = [str(piece["type"]) for piece in pieces]
    empty_regions = {"white": [], "black": []}
    info: dict[str, Any] = {
        "schemaVersion": 1,
        "name": name,
        "template": template,
        "board": {
            "width": width,
            "height": height,
            "startFen": start_fen,
            "chess960": False,
            "twoBoards": False,
            "diagonalLines": [],
        },
        "pieces": deepcopy(pieces),
        "pieceTypes": piece_types,
        "royalPieceTypes": ["king"] if "king" in piece_types else [],
        "movement": {
            "mobilityRegions": {piece_type: deepcopy(empty_regions) for piece_type in piece_types},
            "doubleStep": True,
            "doubleStepRegions": deepcopy(empty_regions),
            "tripleStepRegions": deepcopy(empty_regions),
            "enPassantRegions": deepcopy(empty_regions),
            "enPassantTypes": {"white": ["pawn"], "black": ["pawn"]},
            "pass": {"white": False, "black": False},
            "passOnStalemate": {"white": False, "black": False},
            "mustCapture": False,
            "immobilityIllegal": True,
            "cambodianMoves": False,
            "makpongRule": False,
            "flyingGeneral": False,
            "soldierPromotionRank": 1,
        },
        "promotion": {
            "regions": deepcopy(empty_regions),
            "mainPawnTypes": {"white": "pawn", "black": "pawn"},
            "pawnTypes": {"white": ["pawn"], "black": ["pawn"]},
            "pieceTypes": {
                "white": ["queen", "rook", "bishop", "knight"],
                "black": ["queen", "rook", "bishop", "knight"],
            },
            "promotedPieceTypes": {},
            "limits": {},
            "sittuyin": False,
            "onCapture": False,
            "mandatoryPawn": False,
            "mandatoryPiece": False,
            "demotion": False,
            "shogiStyle": False,
        },
        "capture": {
            "blast": False,
            "blastImmuneTypes": [],
            "mutuallyImmuneTypes": [],
            "petrifyTypes": [],
            "petrifyBlastPieces": False,
        },
        "castling": {
            "enabled": True,
            "droppedPiece": False,
            "kingSideFile": 7,
            "queenSideFile": 3,
            "rank": 1,
            "kingFile": 5,
            "rookKingSideFile": 8,
            "rookQueenSideFile": 1,
            "kingPieces": {"white": "king", "black": "king"},
            "rookPieces": {"white": ["rook"], "black": ["rook"]},
            "opposite": False,
            "wins": {
                "white": {"kingSide": False, "queenSide": False},
                "black": {"kingSide": False, "queenSide": False},
            },
        },
        "drops": {
            "enabled": False,
            "capturesToHand": False,
            "mustDrop": False,
            "mustDropType": "none",
            "dropLoop": False,
            "firstRankPawnDrops": False,
            "promotionZonePawnDrops": False,
            "regions": deepcopy(empty_regions),
            "enclosingRule": "none",
            "enclosingStart": [],
            "sittuyinRook": False,
            "oppositeColoredBishop": False,
            "promoted": False,
            "noDoubledType": "none",
            "noDoubledCount": 1,
            "free": False,
        },
        "gating": {
            "enabled": False,
            "seirawan": False,
            "wallingRule": "none",
            "wallingRegions": deepcopy(empty_regions),
            "wallOrMove": False,
        },
        "gameEnd": {
            "checking": True,
            "dropChecks": True,
            "kingType": "king",
            "nMoveRule": 50,
            "nMoveRuleTypes": {"white": [], "black": []},
            "nFoldRule": 3,
            "nFoldValue": "draw",
            "nFoldValueAbsolute": False,
            "perpetualCheckIllegal": False,
            "moveRepetitionIllegal": False,
            "chasingRule": "none",
            "stalemateValue": "draw",
            "stalematePieceCount": False,
            "checkmateValue": "loss",
            "shogiPawnDropMateIllegal": False,
            "shatarMateRule": False,
            "bikjangRule": False,
            "dupleCheck": False,
            "checkCounting": False,
            "materialCounting": "none",
            "adjudicateFullBoard": False,
            "countingRule": "none",
        },
        "extinction": {
            "value": "none",
            "claim": False,
            "pseudoRoyal": False,
            "pieceTypes": [],
            "pieceCount": 0,
            "opponentPieceCount": 0,
        },
        "flag": {
            "pieces": {"white": "none", "black": "none"},
            "regions": deepcopy(empty_regions),
            "pieceCount": 1,
            "blockedWin": False,
            "move": False,
            "safe": False,
        },
        "connect": {
            "n": 0,
            "pieceTypes": [],
            "horizontal": False,
            "vertical": False,
            "diagonal": False,
            "region1": deepcopy(empty_regions),
            "region2": deepcopy(empty_regions),
            "nxn": 0,
            "collinearN": 0,
            "value": "none",
        },
        "enclosing": {"flipRule": "none"},
        "protocol": {"pieceToCharTable": "-", "pocketSize": 0},
    }
    return info
