blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/aPs8RKr
    about: GitHub issues are meant for tracking enhancements and bugs, not general support. Instead, search the Wiki, StackOverflow, or join our Discord.
