from __future__ import annotations

from typing import Awaitable, Callable, TypeAlias

from aiohttp import web

from bot_api import (
    account,
    playing,
    event_stream,
    game_stream,
    bot_abort,
    bot_resign,
    bot_chat,
    bot_move,
    challenge_accept,
    challenge_decline,
    challenge_create,
    bot_token_test,
)
from account_api import (
    account_close,
    account_close_post,
    account_personal_data,
    account_personal_data_export,
    account_delete,
    account_delete_post,
    account_reopen,
    account_reopen_post,
)
from fishnet import (
    fishnet_monitor,
    fishnet_validate_key,
    fishnet_acquire,
    fishnet_abort,
    fishnet_analysis,
    fishnet_move,
)
from game_api import (
    export_monthly_pgn,
    export_tournament_pgn,
    export_user_pgn,
    export_tournament_trf,
    get_games,
    get_games_by_variant,
    get_user_games,
    get_tournament_games,
    subscribe_games,
    subscribe_invites,
    get_variant_stats,
    cancel_invite,
)
from header_challenges import (
    challenge_seek_accept,
    challenge_seek_cancel,
    challenge_seek_decline,
    get_header_challenges,
    subscribe_challenges,
)
from inbox_api import (
    inbox_unread,
    inbox_threads,
    inbox_thread,
    subscribe_inbox,
    inbox_post,
    inbox_read,
    inbox_delete,
)
from forum import (
    forum_categs,
    forum_captcha,
    forum_captcha_check,
    forum_topics,
    forum_topic,
    forum_search,
    forum_post_redirect,
    forum_topic_create,
    forum_post_create,
    forum_post_edit,
    forum_post_delete,
    forum_topic_participants,
    forum_post_react,
    forum_mod_feed,
    forum_post_relocate,
    forum_topic_close,
    forum_topic_sticky,
)
from report_api import (
    report_create as report_api_create,
    report_queue,
    report_inquiry,
    report_process,
    report_reopen,
    report_silence,
    report_shadowban,
    report_close_account,
)
from mod_public_chat_api import public_chat_timeout
from push_notifications import push_subscribe, service_worker
from utils import import_game, get_names, get_notifications, subscribe_notify, notified
from bug.import_bugh_game import import_game_bpgn
from login import (
    login,
    logout,
    oauth,
    select_username,
    check_username_availability,
    confirm_username,
)
from lang import select_lang
from wsl import lobby_socket_handler
from wsr import round_socket_handler
from tournament.wst import tournament_socket_handler
from simul.wss import simul_socket_handler
from tournament.tournament_calendar import tournament_calendar
from twitch import twitch_request_handler
from puzzle import puzzle_complete, puzzle_vote
from robots import robots
from server_metrics import metrics_handler
from user import (
    block_user,
    follow_user,
    get_blocked_users,
    get_status,
    set_game_category,
    set_pm_friends_only,
    set_theme,
)
from views import (
    about,
    api_docs,
    allplayers,
    analysis,
    arena_new,
    blog,
    blogs,
    calendar,
    contact,
    direct_challenge,
    editor,
    embed,
    faq,
    features,
    game,
    games,
    invite,
    level8win,
    lobby,
    memory,
    paste,
    patron,
    players,
    players50,
    privacy,
    profile,
    report_faq,
    report as report_view,
    reports as reports_view,
    mod_public_chat as mod_public_chat_view,
    user_mini,
    inbox,
    forum,
    forum_etiquette,
    puzzle,
    shields,
    stats,
    tournament,
    tournaments,
    terms,
    tv,
    variants,
    videos,
    video,
    winners,
    ublog,
    simul as simul_view,
)


Handler: TypeAlias = Callable[[web.Request], Awaitable[web.StreamResponse]]
RouteDef: TypeAlias = tuple[str, Handler]


get_routes: tuple[RouteDef, ...] = (
    ("/login/{provider}", login),
    ("/oauth/{provider}", oauth),
    ("/logout", logout),
    ("/account/personal-data", account_personal_data),
    ("/account/personal-data/export", account_personal_data_export),
    ("/account/data", account_personal_data),
    ("/account/data/export", account_personal_data_export),
    ("/account/close", account_close),
    ("/account/delete", account_delete),
    ("/account/reopen", account_reopen),
    ("/select-username", select_username),
    ("/", lobby.lobby),
    ("/about", about.about),
    ("/api", api_docs.api_docs),
    ("/contact", contact.contact),
    ("/terms", terms.terms),
    ("/privacy", privacy.privacy),
    ("/faq", faq.faq),
    ("/page/forum-etiquette", forum_etiquette.forum_etiquette),
    ("/stats", stats.stats),
    ("/players", players.players),
    ("/players/{variant}", players50.players50),
    ("/allplayers", allplayers.allplayers),
    ("/calendar", calendar.calendar),
    ("/features", features.features),
    ("/games", games.games),
    ("/games/{variant}", games.games),
    ("/tv", tv.tv),
    ("/puzzle", puzzle.puzzle),
    ("/puzzle/daily", puzzle.puzzle),
    (r"/puzzle/{puzzleId:\w{5}}", puzzle.puzzle),
    ("/puzzle/{variant}", puzzle.puzzle),
    (r"/corranalysis/{gameId:\w{8}}", analysis.analysis),
    (r"/analysis/{variant:[a-z0-9]+}", analysis.analysis),
    (r"/analysis/{variant:[a-z0-9]+}/{fen}", analysis.analysis),
    ("/seek/{variant}", lobby.lobby),
    (r"/editor/{variant:[a-z0-9]+}", editor.editor),
    (r"/editor/{variant:[a-z0-9]+}/{fen}", editor.editor),
    ("/notifications", get_notifications),
    ("/inbox", inbox.inbox),
    ("/inbox/subscribe", subscribe_inbox),
    ("/inbox/{contact}", inbox.inbox),
    ("/forum", forum.forum),
    ("/forum/search", forum.forum),
    ("/forum/redirect/post/{postId}", forum_post_redirect),
    ("/forum/{categ}/form", forum.forum),
    ("/forum/{categ}/mod-feed", forum.forum),
    ("/forum/{categ}", forum.forum),
    ("/forum/{categ}/{slug}", forum.forum),
    ("/report", report_view.report_form),
    ("/report/faq", report_faq.report_faq),
    ("/report/thanks", report_view.report_thanks),
    ("/reports", reports_view.reports),
    ("/mod/public-chat", mod_public_chat_view.mod_public_chat),
    ("/challenges", get_header_challenges),
    ("/notify", subscribe_notify),
    ("/challenge/subscribe", subscribe_challenges),
    ("/service-worker.js", service_worker),
    (r"/challenge/{seekId:\w+}", direct_challenge.direct_challenge),
    ("/notified", notified),
    (r"/{gameId:\w{8}}", game.game),
    (r"/invite/{gameId:\w{8}}", invite.invite),
    (r"/invite/{gameId:\w{8}}/{player:player[1-2]}", invite.invite),
    (r"/embed/{gameId:\w{8}}", embed.embed),
    ("/tournaments", tournaments.tournaments),
    ("/tournaments/new", arena_new.arena_new),
    (r"/tournaments/{tournamentId:\w{8}}/edit", arena_new.arena_new),
    ("/tournaments/shields", shields.shields),
    ("/tournaments/shields/{variant}", shields.shields),
    ("/tournaments/winners", winners.winners),
    ("/tournaments/winners/{variant}", winners.winners),
    (r"/tournament/{tournamentId:\w{8}}", tournament.tournament),
    (r"/tournament/{tournamentId:\w{8}}/pause", tournament.tournament),
    (r"/tournament/{tournamentId:\w{8}}/cancel", tournament.tournament),
    ("/simul", simul_view.simuls),
    ("/simuls", simul_view.simuls),
    ("/simul/new", simul_view.simul_new),
    (r"/simul/{simulId:\w{8}}", simul_view.simul),
    ("/@/{profileId}", profile.profile),
    ("/@/{profileId}/mini", user_mini.user_mini),
    ("/@/{profileId}/tv", tv.tv),
    ("/@/{profileId}/challenge", lobby.lobby),
    ("/@/{profileId}/challenge/{variant}", lobby.lobby),
    ("/@/{profileId}/play/{variant}", lobby.lobby),
    ("/@/{profileId}/perf/{variant}", profile.profile),
    ("/@/{profileId}/rated", profile.profile),
    ("/@/{profileId}/playing", profile.profile),
    ("/@/{profileId}/me", profile.profile),
    ("/@/{profileId}/import", profile.profile),
    ("/level8win", level8win.level8win),
    ("/patron", patron.patron),
    ("/patron/thanks", patron.patron),
    ("/blogs/image", ublog.image_proxy_external),
    (r"/blogs/image/{postId:\w{8}}", ublog.image_proxy),
    (r"/blogs/discuss/{postId:\w{8}}", ublog.discuss),
    ("/blogs/community", ublog.community),
    ("/blogs/@/{profileId}", ublog.user_blog),
    ("/blogs/@/{profileId}/drafts", ublog.drafts),
    ("/blogs/@/{profileId}/new", ublog.new_form),
    (r"/blogs/@/{profileId}/{postId:\w{8}}/edit", ublog.edit_form),
    (r"/blogs/@/{profileId}/{postId:\w{8}}/like", ublog.like_redirect),
    (r"/blogs/@/{profileId}/{slug}/{postId:\w{8}}", ublog.post),
    ("/blogs", blogs.blogs),
    ("/blogs/{blogId}", blog.blog),
    ("/variants", variants.variants),
    ("/variants/{variant}", variants.variants),
    ("/memory", memory.memory),
    ("/metrics", metrics_handler),
    ("/video", videos.videos),
    ("/video/{videoId}", video.video),
    ("/wsl", lobby_socket_handler),
    ("/wsr/{gameId}", round_socket_handler),
    ("/wst", tournament_socket_handler),
    ("/wss", simul_socket_handler),
    ("/api/account", account),
    ("/api/account/playing", playing),
    ("/api/stream/event", event_stream),
    ("/api/bot/game/stream/{gameId}", game_stream),
    ("/api/blocks", get_blocked_users),
    ("/api/games/user/{profileId}", get_user_games),
    ("/api/games/user/{profileId}/pgn", export_user_pgn),
    ("/api/calendar", tournament_calendar),
    ("/api/stats", get_variant_stats),
    ("/api/stats/humans", get_variant_stats),
    ("/api/games", get_games),
    ("/api/games/{variant}", get_games_by_variant),
    ("/api/users/status", get_status),
    (r"/api/invites/{gameId:\w{8}}", subscribe_invites),
    ("/api/ongoing", subscribe_games),
    ("/api/inbox/unread", inbox_unread),
    ("/api/inbox/threads", inbox_threads),
    ("/api/inbox/thread/{contact}", inbox_thread),
    ("/api/forum/categs", forum_categs),
    ("/api/forum/captcha", forum_captcha),
    ("/api/forum/captcha/{gameId}/check", forum_captcha_check),
    ("/api/forum/search", forum_search),
    ("/api/forum/participants/{topicId}", forum_topic_participants),
    ("/api/forum/{categ}/mod-feed", forum_mod_feed),
    ("/api/forum/{categ}/topics", forum_topics),
    ("/api/forum/{categ}/{slug}", forum_topic),
    ("/api/reports/queue", report_queue),
    ("/api/names", get_names),
    ("/paste", paste.paste),
    (r"/games/export/monthly/{yearmonth:\d{6}}", export_monthly_pgn),
    ("/games/export/tournament/{tournamentId}", export_tournament_pgn),
    ("/games/export/tournament/{tournamentId}/trf", export_tournament_trf),
    ("/tournament/json/{tournamentId}", get_tournament_games),
    ("/fishnet/monitor", fishnet_monitor),
    ("/fishnet/key/{key}", fishnet_validate_key),
    ("/robots.txt", robots),
)

post_routes: tuple[RouteDef, ...] = (
    ("/api/token/test", bot_token_test),
    ("/account/close", account_close_post),
    ("/account/delete", account_delete_post),
    ("/account/reopen", account_reopen_post),
    ("/api/bot/game/{gameId}/abort", bot_abort),
    ("/api/bot/game/{gameId}/resign", bot_resign),
    ("/api/bot/game/{gameId}/chat", bot_chat),
    ("/api/bot/game/{gameId}/move/{move}", bot_move),
    ("/api/challenge/{username}", challenge_create),
    (r"/api/challenge/seek/{seekId:\w+}/accept", challenge_seek_accept),
    (r"/api/challenge/seek/{seekId:\w+}/decline", challenge_seek_decline),
    (r"/api/challenge/seek/{seekId:\w+}/cancel", challenge_seek_cancel),
    (r"/invite/accept/{gameId:\w{8}}", invite.invite),
    (r"/invite/accept/{gameId:\w{8}}/{player:player[1-2]}", invite.invite),
    (r"/invite/cancel/{gameId:\w{8}}", cancel_invite),
    (r"/api/challenge/{gameId:\w{8}}/accept", challenge_accept),
    (r"/api/challenge/{gameId:\w{8}}/decline", challenge_decline),
    ("/api/check-username", check_username_availability),
    ("/api/confirm-username", confirm_username),
    ("/pref/theme", set_theme),
    ("/pref/game-category", set_game_category),
    ("/pref/pm-friends-only", set_pm_friends_only),
    ("/api/{profileId}/block", block_user),
    ("/api/{profileId}/follow", follow_user),
    ("/api/inbox/thread/{contact}", inbox_post),
    ("/api/inbox/thread/{contact}/read", inbox_read),
    ("/api/inbox/thread/{contact}/delete", inbox_delete),
    ("/push/subscribe", push_subscribe),
    ("/api/forum/{categ}/topic", forum_topic_create),
    ("/api/forum/{categ}/{slug}/post", forum_post_create),
    ("/api/forum/post/{postId}/edit", forum_post_edit),
    ("/api/forum/post/{postId}/delete", forum_post_delete),
    ("/api/forum/post/{postId}/relocate", forum_post_relocate),
    ("/api/forum/{categ}/react/{postId}/{reaction}/{v}", forum_post_react),
    ("/api/forum/{categ}/{slug}/close", forum_topic_close),
    ("/api/forum/{categ}/{slug}/sticky", forum_topic_sticky),
    ("/api/report/create", report_api_create),
    ("/report", report_view.report_create),
    (r"/api/reports/{reportId:\w{8}}/inquiry", report_inquiry),
    (r"/api/reports/{reportId:\w{8}}/process", report_process),
    (r"/api/reports/{reportId:\w{8}}/silence", report_silence),
    (r"/api/reports/{reportId:\w{8}}/shadowban", report_shadowban),
    (r"/api/reports/{reportId:\w{8}}/close-account", report_close_account),
    (r"/api/reports/{reportId:\w{8}}/reopen", report_reopen),
    ("/api/mod/public-chat/timeout", public_chat_timeout),
    ("/fishnet/acquire", fishnet_acquire),
    ("/fishnet/analysis/{workId}", fishnet_analysis),
    ("/fishnet/move/{workId}", fishnet_move),
    ("/fishnet/abort/{workId}", fishnet_abort),
    ("/translation/select", select_lang),
    ("/import", import_game),
    ("/import_bpgn", import_game_bpgn),
    ("/simul", simul_view.simuls),
    ("/simuls/simul", simul_view.simuls),
    ("/tournaments/new", tournaments.tournaments),
    (r"/tournaments/{tournamentId:\w{8}}/edit", tournaments.tournaments),
    ("/blogs/@/{profileId}/create", ublog.create),
    (r"/blogs/@/{profileId}/{postId:\w{8}}/edit", ublog.update),
    (r"/blogs/@/{profileId}/{postId:\w{8}}/delete", ublog.delete),
    (r"/blogs/@/{profileId}/{postId:\w{8}}/like", ublog.like),
    ("/twitch", twitch_request_handler),
    (r"/puzzle/complete/{puzzleId:\w{5}}", puzzle_complete),
    (r"/puzzle/vote/{puzzleId:\w{5}}", puzzle_vote),
)
