#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "client" / "nnueCatalog.generated.ts"
HASHED_NNUE_RE = re.compile(r"^.+-([0-9a-f]{12})\.nnue$", re.IGNORECASE)
TS_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _ts_key(value: str) -> str:
    return value if TS_IDENTIFIER_RE.fullmatch(value) else _ts_string(value)


def _load_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError(f"{path} must contain a JSON object")
    return data


def build_catalogue(manifest: dict[str, Any], identities: dict[str, Any]) -> str:
    if manifest.get("schema") != 1:
        raise ValueError("unsupported NNUE manifest schema")
    if identities.get("schema") != 1 or identities.get("fingerprintAlgorithm") != "fsf-ini-v1":
        raise ValueError("unsupported NNUE variant identity schema")

    manifest_networks = manifest.get("networks")
    identity_networks = identities.get("networks")
    aliases = identities.get("aliases")
    if not isinstance(manifest_networks, list) or not isinstance(identity_networks, list):
        raise TypeError("NNUE manifest and identity network lists are required")
    if not isinstance(aliases, dict):
        raise TypeError("NNUE identity aliases must be an object")

    networks: dict[str, tuple[str, int]] = {}
    for item in manifest_networks:
        if not isinstance(item, dict):
            raise TypeError("invalid NNUE manifest network entry")
        network_id = str(item.get("id") or "")
        filename = str(item.get("file") or "")
        size = int(item.get("bytes") or 0)
        digest = str(item.get("sha256") or "").casefold()
        if not network_id or network_id in networks:
            raise ValueError(f"duplicate or empty NNUE network id: {network_id!r}")
        match = HASHED_NNUE_RE.fullmatch(filename)
        if not match:
            raise ValueError(f"NNUE filename has no hash prefix: {filename}")
        if size <= 0:
            raise ValueError(f"NNUE network has invalid size: {filename}")
        if digest and not digest.startswith(match.group(1).casefold()):
            raise ValueError(f"NNUE filename/hash mismatch: {filename}")
        networks[network_id] = (filename, size)

    fingerprints: dict[str, str] = {}
    identity_ids: set[str] = set()
    for item in identity_networks:
        if not isinstance(item, dict):
            raise TypeError("invalid NNUE variant identity entry")
        network_id = str(item.get("id") or "")
        if not network_id or network_id in identity_ids:
            raise ValueError(f"duplicate or empty NNUE identity id: {network_id!r}")
        identity_ids.add(network_id)
        if item.get("kind") == "custom":
            fingerprint = str(item.get("fingerprint") or "").casefold()
            if not re.fullmatch(r"[0-9a-f]{64}", fingerprint):
                raise ValueError(f"invalid fsf-ini-v1 fingerprint for {network_id}")
            fingerprints[network_id] = fingerprint

    if set(networks) != identity_ids:
        missing_identity = sorted(set(networks) - identity_ids)
        missing_network = sorted(identity_ids - set(networks))
        raise ValueError(
            "NNUE manifest/identity ids differ "
            f"(missing identities={missing_identity}, missing networks={missing_network})"
        )

    clean_aliases: dict[str, str] = {}
    for alias, target in aliases.items():
        alias_name = str(alias)
        target_name = str(target)
        if target_name not in networks:
            raise ValueError(f"NNUE alias {alias_name} targets missing network {target_name}")
        clean_aliases[alias_name] = target_name

    lines = [
        "// Generated by scripts/update_nnue_catalogue.py. Do not edit by hand.",
        "",
        "export const OFFICIAL_NNUE_NETWORKS = {",
    ]
    for network_id in sorted(networks):
        filename, size = networks[network_id]
        lines.append(
            f"    {_ts_key(network_id)}: {{ file: {_ts_string(filename)}, bytes: {size} }},"
        )
    lines.extend(
        [
            "} as const;",
            "",
            "export const OFFICIAL_NNUE_CUSTOM_FINGERPRINTS: Readonly<Record<string, string>> = {",
        ]
    )
    for network_id in sorted(fingerprints):
        lines.append(f"    {_ts_key(network_id)}: {_ts_string(fingerprints[network_id])},")
    lines.extend(
        [
            "};",
            "",
            "export const OFFICIAL_NNUE_ENGINE_ALIASES: Readonly<Record<string, string>> = {",
        ]
    )
    for alias in sorted(clean_aliases):
        lines.append(f"    {_ts_key(alias)}: {_ts_string(clean_aliases[alias])},")
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the bundled PyChess NNUE catalogue from Fairy-Stockfish-NNUE-Catalogue metadata."
    )
    parser.add_argument(
        "mirror_repo",
        type=Path,
        help="Path to the gbtami/Fairy-Stockfish-NNUE-Catalogue checkout",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    manifest_path = args.mirror_repo / "manifest.json"
    identities_path = args.mirror_repo / "variant-identities.json"
    catalogue = build_catalogue(_load_json(manifest_path), _load_json(identities_path))
    args.output.write_text(catalogue, encoding="utf-8")

    manifest = _load_json(manifest_path)
    identities = _load_json(identities_path)
    custom_count = sum(1 for item in identities["networks"] if item.get("kind") == "custom")
    print(f"wrote {args.output}")
    print(f"networks: {len(manifest['networks'])}")
    print(f"custom UDV fingerprints: {custom_count}")
    print(f"trusted FSF aliases: {len(identities['aliases'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
